---
version: 1

kind: group

build:
    image: ubuntu:bionic
    build_steps:
        - ./polyaxon_setup.sh

environment:
    resources:
        cpu:
            requests: 1.0
            limits: 2
        memory:
            requests: 3000
            limits: 7000
        gpu: 
            # Need to add GPU nodes to cluster -- can't currently launch them.
            request: 0
            limits: 0

declarations:
    width: 96
    embed_size: 2000
    init_tok2vec: "./RC_2017-01_lmao_glove_cnn_cw96_er2000_cd4_d05.bin"
hptuning:
    concurrency: 100
    random_search:
        n_experiments: 100
    matrix:
        train_iters:
            values: [30]
        train_examples:
            values: [1000]
        batch_size: 
            values: [1, 2, 4, 8, 32, 48, 64]
        dropout:
            values: [0.0, 0.1, 0.2]
        learn_rate:
            values: [0.5, 0.2, 0.15, 0.1, 0.005, 0.002, 0.001, 0.0001]
        b1:
            values: [0.0, 0.1, 0.5, 0.9]
        b2_ratio:
            values: [0.0, 1.0, 1.1, 1.11]
        adam_eps:
            values: [1e-4, 1e-8, 1e-12]
        L2:
            values: [0.0]
 
run:
    cmd: env3.6/bin/python pretrain_textcat.py
